### ISSUE TITLE
Listen issue

### ISSUE THREAD

**Issue by JuandreG** [arduino12/rdm6300#16]
Hello.

When I call rdm6300.listen() I get a error saying 'class Rdm6300 has no member named listen'

I'm trying to use the example provided by you (multiple_software_serials.ino)

How to fix this?

**Comment by arduino12** [comment]
**Hi,**

The [**multiple_software_serials.ino**](https://github.com/arduino12/rdm6300/commit/8053570c51bea88dfea50296f7b8f08e2cbf20fd) was written by @asas1asas200 :)

The [**third line in its doc**](https://github.com/arduino12/rdm6300/blob/master/examples/multiple_software_serials/multiple_software_serials.ino#L3) states that only some boards (like UNO) can listen only on a single software serial at a time..

Which board did you use? (AVR, ESP8266, ESP32..) because the [**software serial is not suported on the ESP32**](https://github.com/arduino12/rdm6300/blob/master/src/rdm6300.h#L14-L15)..
